### ISSUE TITLE
Circular import?

### ISSUE THREAD

**Issue by mmann1123** [jgrss/geosample#2]
I know your busy but just wondering if you have any quick thoughts on this. I have tried installing it in an envrionment a few different ways including 'pip install geosample', pip install git+https://github.com/jgrss/geosample', from a cloned repository 'pip install e .'  all with the sample outcome:
```
from geosample import QuadTree
```
```
ImportError: cannot import name 'QuadTree' from partially initialized module 'geosample' (most likely due to a circular import) (/home/mmann1123/Dropbox/TZ_field_boundaries/geosample.py)
```

**Comment by jgrss** [comment]
I missed this @mmann1123. Do you still have this issue?

**Comment by mmann1123** [comment]
I ended up writing my own crummy version of this, so there is no rush, but my RA and I weren't able to install it.

**Comment by jgrss** [comment]
Okay, I am going to close this for now. See release `v1.0.1`. I was not able to replicate the import error.
